version: '2.2'

services:
  mysql-master:
    build:
      context: ./
      dockerfile: mysql.dockerfile
    hostname: 'master'
    container_name: 'mysql-master'
    ports:
      - '3306'
    volumes:
      - ./master/conf.d:/etc/mysql/mysql.conf.d/
      - ./master/data:/var/lib/mysql
      - ./master/log:/var/log/mysql
      - ./backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=minha_base
    networks:
      - mynet  
  mysql-slave:
    build:
      context: ./
      dockerfile: mysql.dockerfile
    hostname: 'slave'
    container_name: 'mysql-slave'
    ports:
      - '3306'
    volumes:
      - ./slave/conf.d:/etc/mysql/mysql.conf.d/
      - ./slave/data:/var/lib/mysql
      - ./slave/log:/var/log/mysql
      - ./backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=minha_base
    depends_on:
      - mysql-master
    networks:
      - mynet  

networks:
  mynet:      